version: "3"
name: pokemon-list
services:
  mongo-db:
    container_name: pokemon-db
    image: mongo
    environment:
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      - MONGO_INITDB_DATABASE=pokemon
      - MONGO_INITDB_ROOT_USERNAME=pokemon
      - MONGO_INITDB_ROOT_PASSWORD=pokemon123456789$
    volumes:
      - mongodb-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: always
    ports:
      - "27017:27017"
  api:
    build: pokemon-api-express
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo-db
    environment:
      Database_Server: pokemon-db
    container_name: pokemon-api
  app:
    build: pokemon-app-react
    restart: always
    ports:
      - "3000:3000"
    container_name: pokemon-app
volumes:
  mongodb-volume:

