version: "3"
name: pokemon-list
services:
  db:
    image: mongo
    restart: always
    container_name: pokemon-db
    environment:
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      - MONGO_INITDB_DATABASE=pokemon
      - MONGO_INITDB_ROOT_USERNAME=pokemon
      - MONGO_INITDB_ROOT_PASSWORD=pokemon123456789$
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
  api:
    build: pokemon-api-express
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      Database_Server: pokemon-db
    container_name: pokemon-api
